# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e05cae22af18b71560b8ad46d187a67d2ed504a5c90fb23d89c1c96307042e2ced41ccd5f6b082691104a25cfe5bcdd1aa6e7352c359ef62654bedb34b4220b

test:
  secret_key_base: e534e707bb0c44885d47aeeb8e2e372dc7ae530acb3a5ed26cf2ad4f23d36e441040c06e5c39a7fbbb2935dc6997d0a2ad71be144db56239c7616516b2535cad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
